name: flutter_infinite_list
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.1.0
  equatable: ^2.0.3
  nb_utils: ^4.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  http: ^0.13.0
  stream_transform: ^2.0.0
  firebase_core: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/roomFinding/
