name: hoot
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.1.0
  equatable: ^2.0.3
  nb_utils: ^4.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  http: ^0.13.0
  stream_transform: ^2.0.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  build_runner: ^2.1.11
  fluttertoast: ^8.1.1
  test: ^1.14.4
  fake_cloud_firestore: ^2.0.1
  mockito: ^5.3.2
  datetime_picker_formfield: ^2.0.0
  image_picker: ^0.8.6
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/roomFinding/
